// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Sidebar for ROS 2 content
  ros2Sidebar: [
    {
      type: 'category',
      label: 'ROS 2 for Humanoid Robotics',
      items: [
        'ros2-humanoid/intro-to-ros2',
        'ros2-humanoid/communication-model',
        'ros2-humanoid/robot-structure-urdf',
      ],
    },
  ],

  // Sidebar for Digital Twin content
  digitalTwinSidebar: [
    {
      type: 'category',
      label: 'Digital Twin Simulation (Gazebo & Unity)',
      items: [
        'digital-twin/physics-simulation-gazebo',
        'digital-twin/digital-twins-hri-unity',
        'digital-twin/sensor-simulation-validation',
      ],
    },
  ],

  // Sidebar for AI-Robot Brain content
  aiRobotBrainSidebar: [
    {
      type: 'category',
      label: 'AI-Robot Brain (NVIDIA Isaac™)',
      items: [
        'ai-robot-brain/isaac-sim-synthetic-data',
        'ai-robot-brain/isaac-ros-perception-vslam',
        'ai-robot-brain/nav2-humanoid-navigation',
      ],
    },
  ],

  // Sidebar for Vision-Language-Action content
  vlaModuleSidebar: [
    {
      type: 'category',
      label: 'Vision-Language-Action (VLA) Module',
      items: [
        'vla-module/voice-to-action-whisper',
        'vla-module/llm-cognitive-planning',
        'vla-module/capstone-autonomous-humanoid',
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
